# Generated by Django 2.2 on 2020-11-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='website',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
