# Generated by Django 2.2 on 2020-12-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20201119_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='actif',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
