# Generated by Django 2.2 on 2021-03-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20201224_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='comment',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='payments_conditions',
            field=models.CharField(choices=[('30', '30 days'), ('END', 'End of the current month')], max_length=2, null=True),
        ),
    ]
