# Generated by Django 2.2 on 2021-03-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20210318_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='payments_conditions',
            field=models.CharField(choices=[('30', '30 days'), ('END', 'End of the current month')], max_length=10, null=True),
        ),
    ]
