# Generated by Django 3.2 on 2021-04-28 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels', models.CharField(choices=[('Friendly\xa0reminder', 'Friendly\xa0reminder'), ('Your invoice is overdue', 'Your invoice is overdue'), ('Your invoice is overdue II', 'Your invoice is overdue II'), ('Urgent overdue invoice', 'Urgent overdue invoice')], max_length=100)),
                ('text', froala_editor.fields.FroalaField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
