# Generated by Django 3.2 on 2021-04-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='levels',
            field=models.CharField(choices=[('Friendly\xa0reminder', 'Friendly\xa0reminder'), ('Your invoice is overdue', 'Your invoice is overdue'), ('Your invoice is overdue II', 'Your invoice is overdue II'), ('Urgent overdue invoice', 'Urgent overdue invoice')], max_length=100, unique=True),
        ),
    ]
