# Generated by Django 3.2 on 2021-04-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_alter_texts_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='text',
            field=models.TextField(),
        ),
    ]
