# Generated by Django 2.2 on 2020-11-26 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_auto_20201119_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('dateCreation', models.DateField(auto_now_add=True)),
                ('number', models.CharField(max_length=150)),
                ('client', models.ForeignKey(choices=[('pyd', 'payed'), ('npyd', 'notPayed'), ('cnl', 'canceled')], default='notPayed', on_delete=django.db.models.deletion.CASCADE, to='clients.Clients')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ModelName',
                'verbose_name_plural': 'ModelNames',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
