# Generated by Django 3.2 on 2021-04-20 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '__first__'),
        ('clients', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('dateCreation', models.DateField(auto_now_add=True)),
                ('stats', models.CharField(choices=[('rej', 'rejected'), ('inw', 'in wait'), ('acc', 'accepted')], default='inw', max_length=100)),
                ('number', models.CharField(max_length=150, unique=True)),
                ('artice', models.ManyToManyField(to='stocks.Article')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('dateCreation', models.DateField()),
                ('stats', models.CharField(choices=[('payed', 'pyd'), ('notPayed', 'npyd'), ('canceled', 'cnl')], default='notPayed', max_length=100)),
                ('prov_numb', models.CharField(blank=True, max_length=150, null=True)),
                ('number', models.CharField(blank=True, max_length=150, null=True)),
                ('fnb', models.CharField(blank=True, max_length=150, null=True)),
                ('back_status', models.CharField(blank=True, choices=[('Finilised', 'fnsh'), ('In save', 'insv'), ('In Process', 'inpro')], max_length=100, null=True)),
                ('deadlinePay', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True)),
                ('tax_one', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True)),
                ('tax_two', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article_Inv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_one', models.IntegerField(blank=True, default=0, null=True)),
                ('tax_two', models.IntegerField(blank=True, default=0, null=True)),
                ('remise', models.IntegerField(blank=True, default=0, null=True)),
                ('qte', models.IntegerField(blank=True, default=1, null=True)),
                ('amount', models.CharField(max_length=50, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.article')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.invoices')),
            ],
            options={
                'unique_together': {('invoice', 'article')},
            },
        ),
    ]
