# Generated by Django 2.2 on 2020-11-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoices',
            options={},
        ),
        migrations.AlterModelTable(
            name='invoices',
            table=None,
        ),
    ]
