# Generated by Django 3.2 on 2021-04-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_invoices_still_to_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='stats',
            field=models.CharField(choices=[('payed', 'pyd'), ('notPayed', 'npyd'), ('canceled', 'cnl'), ('partial payed', 'part-payed')], default='notPayed', max_length=100),
        ),
    ]
