# Generated by Django 2.2 on 2020-11-26 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_auto_20201126_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='stats',
            field=models.CharField(choices=[('pyd', 'payed'), ('npyd', 'notPayed'), ('cnl', 'canceled')], default='npyd', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Clients'),
        ),
    ]
