# Generated by Django 3.2 on 2021-04-29 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_paymentsmethods'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docs.paymentsmethods'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='stats',
            field=models.CharField(choices=[('payed', 'pyd'), ('unpaied', 'npyd'), ('canceled', 'cnl'), ('partial payed', 'part-payed')], default='unpaid', max_length=100),
        ),
    ]
