# Generated by Django 2.2 on 2020-11-29 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_auto_20201119_1153'),
        ('docs', '0005_auto_20201126_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('dateCreation', models.DateField(auto_now_add=True)),
                ('stats', models.CharField(choices=[('rej', 'rejected'), ('inw', 'in wait'), ('acc', 'accepted')], default='npyd', max_length=100)),
                ('number', models.CharField(max_length=150, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Clients')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
