# Generated by Django 3.2 on 2021-04-29 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
        ('docs', '0006_auto_20210429_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='artice',
        ),
        migrations.AddField(
            model_name='quotes',
            name='back_status',
            field=models.CharField(blank=True, choices=[('Finilised', 'fnsh'), ('In save', 'insv'), ('In Process', 'inpro')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='fnb',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docs.paymentsmethods'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='prov_numb',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotes',
            name='sub_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='tax_one',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='tax_two',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clients'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='dateCreation',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='stats',
            field=models.CharField(choices=[('rejected', 'rejected'), ('in wait', 'in wait'), ('accepted', 'accepted')], default='in wait', max_length=100),
        ),
        migrations.CreateModel(
            name='Article_Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_one', models.IntegerField(blank=True, default=0, null=True)),
                ('tax_two', models.IntegerField(blank=True, default=0, null=True)),
                ('remise', models.IntegerField(blank=True, default=0, null=True)),
                ('qte', models.IntegerField(blank=True, default=1, null=True)),
                ('amount', models.CharField(max_length=50, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.article')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.quotes')),
            ],
            options={
                'unique_together': {('quote', 'article')},
            },
        ),
    ]
