# Generated by Django 2.2 on 2020-12-11 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20201207_1700'),
        ('docs', '0006_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='artice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.Article'),
        ),
    ]
