# Generated by Django 2.2 on 2020-12-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20201207_1700'),
        ('docs', '0007_invoices_artice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='artice',
        ),
        migrations.AddField(
            model_name='invoices',
            name='artice',
            field=models.ManyToManyField(to='stocks.Article'),
        ),
    ]
