# Generated by Django 2.2 on 2020-12-18 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_auto_20201211_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='dateCreation',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='number',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
