# Generated by Django 2.2 on 2020-12-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_auto_20201218_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='dateCreation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
