# Generated by Django 2.2 on 2020-12-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20201207_1700'),
        ('docs', '0010_auto_20201218_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='artice',
            field=models.ManyToManyField(to='stocks.Article'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='stats',
            field=models.CharField(choices=[('rej', 'rejected'), ('inw', 'in wait'), ('acc', 'accepted')], default='inw', max_length=100),
        ),
    ]
