# Generated by Django 2.2 on 2020-12-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0011_auto_20201220_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='back_status',
            field=models.CharField(choices=[('pyd', 'payed'), ('npyd', 'notPayed'), ('cnl', 'canceled')], default='insv', max_length=100),
        ),
    ]
