# Generated by Django 2.2 on 2020-12-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0012_invoices_back_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='back_status',
            field=models.CharField(blank=True, choices=[('pyd', 'payed'), ('npyd', 'notPayed'), ('cnl', 'canceled')], default='insv', max_length=100, null=True),
        ),
    ]
