# Generated by Django 2.2 on 2020-12-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0013_auto_20201221_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='back_status',
            field=models.CharField(blank=True, choices=[('fnsh', 'finished'), ('insv', 'insave')], max_length=100, null=True),
        ),
    ]
