# Generated by Django 2.2 on 2020-12-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0014_auto_20201221_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='back_status',
            field=models.CharField(blank=True, choices=[('finished', 'fnsh'), ('insave', 'insv')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='stats',
            field=models.CharField(choices=[('payed', 'pyd'), ('notPayed', 'npyd'), ('canceled', 'cnl')], default='npyd', max_length=100),
        ),
    ]
