# Generated by Django 2.2 on 2020-12-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0015_auto_20201222_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='stats',
            field=models.CharField(choices=[('payed', 'pyd'), ('notPayed', 'npyd'), ('canceled', 'cnl')], default='notPayed', max_length=100),
        ),
    ]
