# Generated by Django 2.2 on 2020-12-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0016_auto_20201222_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='dateCreation',
            field=models.DateField(),
        ),
    ]
