# Generated by Django 2.2 on 2020-12-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0018_invoices_fnb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='fnb',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
