# Generated by Django 2.2 on 2021-01-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0019_auto_20201231_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='prov_numb',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
