# Generated by Django 2.2 on 2021-01-11 16:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docs', '0021_article_inv'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article_inv',
            unique_together={('invoice', 'article')},
        ),
    ]
