# Generated by Django 2.2 on 2021-01-11 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0022_auto_20210111_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='artice',
        ),
    ]
