# Generated by Django 2.2 on 2021-01-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0023_remove_invoices_artice'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_inv',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
