# Generated by Django 2.2 on 2021-01-13 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0024_article_inv_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_inv',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Article'),
        ),
    ]
