# Generated by Django 2.2 on 2021-01-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0026_auto_20210113_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_inv',
            name='qte',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='article_inv',
            name='remise',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='article_inv',
            name='tax_one',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='article_inv',
            name='tax_two',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
