# Generated by Django 2.2 on 2021-02-10 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0027_auto_20210113_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Clients'),
        ),
    ]
