# Generated by Django 2.2 on 2021-03-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0028_auto_20210210_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_inv',
            name='price',
        ),
        migrations.AddField(
            model_name='article_inv',
            name='amount',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
