# Generated by Django 2.2 on 2021-03-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0029_auto_20210309_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='back_status',
            field=models.CharField(blank=True, choices=[('Finilised', 'fnsh'), ('In save', 'insv'), ('In Process', 'inpro')], max_length=100, null=True),
        ),
    ]
