# Generated by Django 2.2 on 2021-03-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0030_auto_20210316_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='deadlinePay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
