# Generated by Django 2.2 on 2021-04-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0031_invoices_deadlinepay'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='sub_total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='tax_one',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='tax_two',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
