# Generated by Django 2.2 on 2021-04-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0033_auto_20210401_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='tax_one',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='tax_two',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='total',
        ),
        migrations.AddField(
            model_name='article_inv',
            name='sub_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='article_inv',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='article_inv',
            name='tax_one',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='article_inv',
            name='tax_two',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
