# Generated by Django 2.2 on 2020-11-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201117_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='adress',
            field=models.TextField(),
        ),
    ]
