# Generated by Django 2.2 on 2020-12-01 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleType', models.CharField(choices=[('srv', 'service'), ('prod', 'product')], default='srv', max_length=100)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('priceNtax', models.DecimalField(decimal_places=10, max_digits=19)),
                ('tax', models.IntegerField(blank=True)),
                ('buyPrice', models.DecimalField(decimal_places=10, max_digits=19)),
                ('gainMargin', models.DecimalField(decimal_places=10, max_digits=19)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Units')),
            ],
        ),
    ]
