# Generated by Django 3.2 on 2021-04-20 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('value', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleType', models.CharField(choices=[('service', 'srv'), ('product', 'prod')], max_length=100)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('ref', models.CharField(blank=True, max_length=150)),
                ('actif', models.BooleanField(default=True, null=True)),
                ('buyPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('gainMargin', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('sellPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.units')),
            ],
        ),
    ]
