# Generated by Django 2.2 on 2020-12-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20201207_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='buyPrice',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='article',
            name='gainMargin',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='article',
            name='priceNtax',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='article',
            name='sellPrice',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
