# Generated by Django 2.2 on 2020-12-24 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20201207_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='priceNtax',
        ),
    ]
