# Generated by Django 2.2 on 2020-12-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_remove_article_pricentax'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ref',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
