# Generated by Django 2.2 on 2020-12-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_auto_20201225_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='actif',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
