# Generated by Django 2.2 on 2021-01-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_article_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tax_two',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
