# Generated by Django 2.2 on 2021-01-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_article_tax_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tax',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
