# Generated by Django 2.2 on 2021-01-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_auto_20210108_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('value', models.IntegerField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='tax_two',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tax',
        ),
        migrations.AddField(
            model_name='article',
            name='tax',
            field=models.ManyToManyField(to='stocks.Tax'),
        ),
    ]
