# Generated by Django 2.2 on 2021-01-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_auto_20210108_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tax',
        ),
    ]
