# Generated by Django 2.2 on 2021-03-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_remove_article_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleType',
            field=models.CharField(choices=[('service', 'srv'), ('product', 'prod')], max_length=100),
        ),
    ]
